name: swastha
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^1.17.1
  firebase_auth: ^3.3.16
  flutter_bloc: ^8.0.1
  firebase_storage: ^10.2.14
  cloud_firestore: ^3.1.13
  image_picker: ^0.8.5
  image_cropper: ^2.0.0
  equatable: ^2.0.3
  flutter_zoom_drawer: ^3.0.2
  flutter_advanced_drawer: ^1.3.2
  flutter_spinkit: ^5.1.0
  syncfusion_flutter_gauges: ^20.1.56
  shared_preferences: ^2.0.15
  google_sign_in: ^5.3.1
  sqflite: ^2.0.2+1
  path_provider: ^2.0.11
  sensors_plus: ^1.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/